apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-manager # necessary for Kustomize identification
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/em-test-dev/employee-manager:dawid
        name: employee-manager # necessary for Kustomize identification
