apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: employee-manager-ci-dev
  namespace: em-test-dev
spec:
  params:
    - default: employee-manager
      name: APP_NAME
      type: string
    - default: 'https://github.com/devopski/employee-manager-h2db.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/em-test-dev/employee-manager
      name: IMAGE_NAME
      type: string
    - default: latest
      name: IMAGE_TAG
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: openjdk-17-ubi8
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
