apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-manager
spec:
  selector:
    matchLabels:
      app: employee-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-manager
    spec:
      containers:
      - name: employee-manager
        image: image-registry.openshift-image-registry.svc:5000/em-test-dev/employee-manager
